import {} from "react";
import SkillCard from "../SkillCard";

interface SkillsProps {}

export default function Skills({}: SkillsProps) {
  return (
    <div
      id="skills"
      className={`flex flex-col w-full mt-20 bg-gradient-to-r from-sky-500 to-violet-500 `}
    >
      <h1 id="about" className="text-5xl font-bold mx-auto my-3 text-white">
        💻 Skills & <span className="text-rose-800">Abilities</span>
      </h1>

      <div className="bg-black/50 h-full my-4 mx-28 rounded-2xl p-5 flex flex-wrap gap-3 justify-center">
        <SkillCard
          name="ReactJS"
          image={`https://res.cloudinary.com/dzdqy3wfg/image/upload/v1688538983/react-svgrepo-com_ynkbwr.svg`}
        />
        <SkillCard
          name="ReactJS"
          image={`https://res.cloudinary.com/dzdqy3wfg/image/upload/v1688538983/react-svgrepo-com_ynkbwr.svg`}
        />
        <SkillCard
          name="ReactJS"
          image={`https://res.cloudinary.com/dzdqy3wfg/image/upload/v1688538983/react-svgrepo-com_ynkbwr.svg`}
        />
        <SkillCard
          name="ReactJS"
          image={`https://res.cloudinary.com/dzdqy3wfg/image/upload/v1688538983/react-svgrepo-com_ynkbwr.svg`}
        />
        <SkillCard
          name="ReactJS"
          image={`https://res.cloudinary.com/dzdqy3wfg/image/upload/v1688538983/react-svgrepo-com_ynkbwr.svg`}
        />
        <SkillCard
          name="ReactJS"
          image={`https://res.cloudinary.com/dzdqy3wfg/image/upload/v1688538983/react-svgrepo-com_ynkbwr.svg`}
        />
        <SkillCard
          name="ReactJS"
          image={`https://res.cloudinary.com/dzdqy3wfg/image/upload/v1688538983/react-svgrepo-com_ynkbwr.svg`}
        />
        <SkillCard
          name="ReactJS"
          image={`https://res.cloudinary.com/dzdqy3wfg/image/upload/v1688538983/react-svgrepo-com_ynkbwr.svg`}
        />
        <SkillCard
          name="ReactJS"
          image={`https://res.cloudinary.com/dzdqy3wfg/image/upload/v1688538983/react-svgrepo-com_ynkbwr.svg`}
        />
        <SkillCard
          name="ReactJS"
          image={`https://res.cloudinary.com/dzdqy3wfg/image/upload/v1688538983/react-svgrepo-com_ynkbwr.svg`}
        />
        <SkillCard
          name="ReactJS"
          image={`https://res.cloudinary.com/dzdqy3wfg/image/upload/v1688538983/react-svgrepo-com_ynkbwr.svg`}
        />
        <SkillCard
          name="ReactJS"
          image={`https://res.cloudinary.com/dzdqy3wfg/image/upload/v1688538983/react-svgrepo-com_ynkbwr.svg`}
        />
        <SkillCard
          name="ReactJS"
          image={`https://res.cloudinary.com/dzdqy3wfg/image/upload/v1688538983/react-svgrepo-com_ynkbwr.svg`}
        />
        <SkillCard
          name="ReactJS"
          image={`https://res.cloudinary.com/dzdqy3wfg/image/upload/v1688538983/react-svgrepo-com_ynkbwr.svg`}
        />
        <SkillCard
          name="ReactJS"
          image={`https://res.cloudinary.com/dzdqy3wfg/image/upload/v1688538983/react-svgrepo-com_ynkbwr.svg`}
        />
        <SkillCard
          name="ReactJS"
          image={`https://res.cloudinary.com/dzdqy3wfg/image/upload/v1688538983/react-svgrepo-com_ynkbwr.svg`}
        />
        <SkillCard
          name="ReactJS"
          image={`https://res.cloudinary.com/dzdqy3wfg/image/upload/v1688538983/react-svgrepo-com_ynkbwr.svg`}
        />
        <SkillCard
          name="ReactJS"
          image={`https://res.cloudinary.com/dzdqy3wfg/image/upload/v1688538983/react-svgrepo-com_ynkbwr.svg`}
        />
        <SkillCard
          name="ReactJS"
          image={`https://res.cloudinary.com/dzdqy3wfg/image/upload/v1688538983/react-svgrepo-com_ynkbwr.svg`}
        />
        <SkillCard
          name="ReactJS"
          image={`https://res.cloudinary.com/dzdqy3wfg/image/upload/v1688538983/react-svgrepo-com_ynkbwr.svg`}
        />
        <SkillCard
          name="ReactJS"
          image={`https://res.cloudinary.com/dzdqy3wfg/image/upload/v1688538983/react-svgrepo-com_ynkbwr.svg`}
        />
        <SkillCard
          name="ReactJS"
          image={`https://res.cloudinary.com/dzdqy3wfg/image/upload/v1688538983/react-svgrepo-com_ynkbwr.svg`}
        />
        <SkillCard
          name="ReactJS"
          image={`https://res.cloudinary.com/dzdqy3wfg/image/upload/v1688538983/react-svgrepo-com_ynkbwr.svg`}
        />
        <SkillCard
          name="ReactJS"
          image={`https://res.cloudinary.com/dzdqy3wfg/image/upload/v1688538983/react-svgrepo-com_ynkbwr.svg`}
        />
        <SkillCard
          name="ReactJS"
          image={`https://res.cloudinary.com/dzdqy3wfg/image/upload/v1688538983/react-svgrepo-com_ynkbwr.svg`}
        />
        <SkillCard
          name="ReactJS"
          image={`https://res.cloudinary.com/dzdqy3wfg/image/upload/v1688538983/react-svgrepo-com_ynkbwr.svg`}
        />
        <SkillCard
          name="ReactJS"
          image={`https://res.cloudinary.com/dzdqy3wfg/image/upload/v1688538983/react-svgrepo-com_ynkbwr.svg`}
        />
        <SkillCard
          name="ReactJS"
          image={`https://res.cloudinary.com/dzdqy3wfg/image/upload/v1688538983/react-svgrepo-com_ynkbwr.svg`}
        />
        <SkillCard
          name="ReactJS"
          image={`https://res.cloudinary.com/dzdqy3wfg/image/upload/v1688538983/react-svgrepo-com_ynkbwr.svg`}
        />
        <SkillCard
          name="ReactJS"
          image={`https://res.cloudinary.com/dzdqy3wfg/image/upload/v1688538983/react-svgrepo-com_ynkbwr.svg`}
        />
        <SkillCard
          name="ReactJS"
          image={`https://res.cloudinary.com/dzdqy3wfg/image/upload/v1688538983/react-svgrepo-com_ynkbwr.svg`}
        />
        <SkillCard
          name="ReactJS"
          image={`https://res.cloudinary.com/dzdqy3wfg/image/upload/v1688538983/react-svgrepo-com_ynkbwr.svg`}
        />
        <SkillCard
          name="ReactJS"
          image={`https://res.cloudinary.com/dzdqy3wfg/image/upload/v1688538983/react-svgrepo-com_ynkbwr.svg`}
        />
        <SkillCard
          name="ReactJS"
          image={`https://res.cloudinary.com/dzdqy3wfg/image/upload/v1688538983/react-svgrepo-com_ynkbwr.svg`}
        />
        <SkillCard
          name="ReactJS"
          image={`https://res.cloudinary.com/dzdqy3wfg/image/upload/v1688538983/react-svgrepo-com_ynkbwr.svg`}
        />
        <SkillCard
          name="ReactJS"
          image={`https://res.cloudinary.com/dzdqy3wfg/image/upload/v1688538983/react-svgrepo-com_ynkbwr.svg`}
        />
        <SkillCard
          name="ReactJS"
          image={`https://res.cloudinary.com/dzdqy3wfg/image/upload/v1688538983/react-svgrepo-com_ynkbwr.svg`}
        />
        <SkillCard
          name="ReactJS"
          image={`https://res.cloudinary.com/dzdqy3wfg/image/upload/v1688538983/react-svgrepo-com_ynkbwr.svg`}
        />
        <SkillCard
          name="ReactJS"
          image={`https://res.cloudinary.com/dzdqy3wfg/image/upload/v1688538983/react-svgrepo-com_ynkbwr.svg`}
        />
      </div>
    </div>
  );
}
